inhibit_all_warnings!
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'iitp.infection.pm' do
    use_frameworks!

    #pod 'Zip'

    pod 'iOSDFULibrary'
	
    pod 'iOSOTARTK'

end


